import React from 'react'

export default function AboutApp() {
    return (
        <div className="pt-5">
            <div className="container text-light text-left">
                <h2 className="display-4 mt-5 mb-4">About Beastbase</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Nibh ipsum consequat nisl vel pretium lectus. Leo urna molestie at elementum eu facilisis. Sem integer vitae justo eget magna fermentum iaculis. Interdum posuere lorem ipsum dolor. Vivamus at augue eget arcu dictum varius duis at. Urna neque viverra justo nec ultrices dui sapien. Ultrices in iaculis nunc sed augue lacus viverra. Mattis enim ut tellus elementum sagittis vitae. Facilisis mauris sit amet massa vitae tortor condimentum lacinia quis. Arcu risus quis varius quam quisque id diam. Ullamcorper a lacus vestibulum sed. Sed risus pretium quam vulputate dignissim. Ut aliquam purus sit amet. Pulvinar elementum integer enim neque volutpat.</p>
                <p>Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Amet est placerat in egestas erat imperdiet. Id consectetur purus ut faucibus pulvinar elementum. Rutrum tellus pellentesque eu tincidunt tortor. Lorem ipsum dolor sit amet consectetur. Lectus arcu bibendum at varius vel. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt. Massa enim nec dui nunc mattis enim ut tellus. Tempor orci dapibus ultrices in iaculis. Risus pretium quam vulputate dignissim. Mattis molestie a iaculis at erat pellentesque. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Dis parturient montes nascetur ridiculus mus mauris. Fames ac turpis egestas integer eget. Nam libero justo laoreet sit amet cursus sit amet dictum. Odio aenean sed adipiscing diam donec adipiscing tristique. Non curabitur gravida arcu ac tortor dignissim convallis aenean. Dictum non consectetur a erat.</p>
                <p>Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Odio ut enim blandit volutpat maecenas. Habitant morbi tristique senectus et netus et malesuada. Vitae turpis massa sed elementum tempus egestas sed sed. Faucibus interdum posuere lorem ipsum dolor sit amet. Velit scelerisque in dictum non consectetur a erat nam. Eget nullam non nisi est. Convallis aenean et tortor at risus viverra. Arcu cursus vitae congue mauris rhoncus. Vitae tempus quam pellentesque nec. Blandit turpis cursus in hac habitasse platea.</p>
                <p>Mauris in aliquam sem fringilla. Aenean sed adipiscing diam donec adipiscing tristique risus nec. Commodo ullamcorper a lacus vestibulum sed. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Ultrices vitae auctor eu augue ut lectus arcu. Volutpat diam ut venenatis tellus in metus. Vestibulum morbi blandit cursus risus at. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Neque aliquam vestibulum morbi blandit cursus risus at. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit amet.</p>
            </div>
        </div>
    )
}
